/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.4.6. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  BTN_1
    , input  BTN_2

      // Outputs
    , output wire  LED_1
    , output wire  LED_2
    );
  // src/Button.hs:15:1-9
  wire  btn1;
  // src/Button.hs:15:1-9
  wire  btn2;
  wire [1:0] BTN;
  wire [1:0] LED;

  assign BTN = {BTN_1,   BTN_2};

  assign btn1 = BTN[1:1];

  assign btn2 = BTN[0:0];

  assign LED = {btn1 & btn2,   btn1 | btn2};

  assign LED_1 = LED[1:1];

  assign LED_2 = LED[0:0];


endmodule

